name: Gear builder

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - 'master'
      - 'dev'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Get Docs
          run: git submodule update --init
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
        env:
          CI: true
          API_ROOT: dash.gearbot.rocks
          API_SECURE: true
          CORS: false
