name: Gear builder

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - 'master'
      - 'dev'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Get Docs
        run: git submodule update --init
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Get translations from Crowdin
          run: |
            curl https://api.crowdin.com/api/project/gearbot/export?login=gearbot&account-key=${{secrets.crowdin_api_key}}
            wget -O all.zip "https://api.crowdin.com/api/project/gearbot/download/all.zip?login=gearbot&account-key=${{secrets.crowdin_api_key}}"
            unzip all.zip -d src/assets
      - name: preact env info
        run: preact info
      - run: npm run build
        env:
          CI: true
          API_ROOT: staging.gearbot.rocks
          API_SECURE: true
          CORS: false
          SENTRY_DSN: ${{secrets.SENTRY_DSN}}
      - name: deploy to server
          uses: AEnterprise/rsync-deploy@v1.0
          env:
            DEPLOY_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-e -c -r --delete"
            SERVER_PORT: ${{ secrets.SERVER_PORT }}
            FOLDER: "build/"
            SERVER_IP: ${{ secrets.SERVER_IP }}
            USERNAME: ${{ secrets.USERNAME }}
            SERVER_DESTINATION: ${{ secrets.SERVER_DESTINATION_STAGING }}
            VERSIONCHECK: true
            - name: Purge Cloudflare Cache
              uses: jakejarvis/cloudflare-purge-action@v0.1.1
              env:
                CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
                CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
                CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
